version: '3.3'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:15
    restart: always
    env_file:
      - .env
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    image: anyashmykova/foodgram_backend:latest
    restart: always
    env_file:
      - .env
    volumes:
      - static:/static
      - media:/media
    depends_on:
      - db

  frontend:
    image: anyashmykova/foodgram_frontend:latest
    restart: always
    container_name: foodgram-front
    volumes:
      - ../frontend/:/app/result_build/

  nginx:
    image: anyashmykova/foodgram_gateway:latest
    restart: always
    container_name: foodgram-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static:/static
      - media:/media
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - backend
      - frontend