# Generated by Django 5.2.8 on 2026-06-26 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_alter_favorite_options_alter_ingredient_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='short_link',
            field=models.SlugField(blank=True, max_length=16, null=True, unique=True, verbose_name='Короткая ссылка'),
        ),
    ]
